#!/usr/bin/env python

#
# Low-budget version bumper for Noisemaker.
#
# Enable this hook in your workspace. At the project root, run:
# pushd .git/hooks && ln -s ../../hooks/pre-commit pre-commit && popd
#

import re
import shutil
import subprocess


def main():
    with open('setup.py', 'r') as setup:
        with open('setup.py-out', 'w') as out:
            for line in setup:
                m = re.match("(\s+version=['\"](\d+\.)*)(\d+)(['\"],{0,1})$", line)

                if m:
                    out.write("%s%s%s\n" % (m.group(1), int(m.group(3)) + 1, m.group(4)))
                else:
                    out.write(line)

    shutil.move('setup.py-out', 'setup.py')

    subprocess.check_call(["python", "setup.py", "test"])

    subprocess.call(["git", "add", "setup.py"])


main()
