// Outline final blend shader
// Performs: out = (invert ? (1.0 - edges) : edges) * base
// Edges texture is generated by preceding multi-pass pipeline (value map + sobel combine)

const CHANNEL_COUNT : u32 = 4u;

struct OutlineParams {
    width : f32,
    height : f32,
    channel_count : f32,
    invert_flag : f32,
    sobel_metric : f32,
    _pad0 : f32,
    time : f32,
    speed : f32,
};

@group(0) @binding(0) var base_texture : texture_2d<f32>;
@group(0) @binding(1) var<storage, read_write> output_buffer : array<f32>;
@group(0) @binding(2) var<uniform> params : OutlineParams;
@group(0) @binding(3) var edges_texture : texture_2d<f32>;

fn write_pixel(base_index : u32, color : vec4<f32>) {
    output_buffer[base_index + 0u] = color.x;
    output_buffer[base_index + 1u] = color.y;
    output_buffer[base_index + 2u] = color.z;
    output_buffer[base_index + 3u] = color.w;
}

@compute @workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) gid : vec3<u32>) {
    let width : u32 = max(u32(params.width), 1u);
    let height : u32 = max(u32(params.height), 1u);
    if (gid.x >= width || gid.y >= height) { return; }

    let coord : vec2<i32> = vec2<i32>(i32(gid.x), i32(gid.y));
    let base : vec4<f32> = textureLoad(base_texture, coord, 0);
    let edges : vec4<f32> = textureLoad(edges_texture, coord, 0);


    // Clamp edges (already normalized from sobel combine + optional normalize pass upstream)
    let e : vec3<f32> = clamp(edges.xyz, vec3<f32>(0.0), vec3<f32>(1.0));
    // Black-edge overlay: darken base where edges are present
    let s : f32 = max(e.x, max(e.y, e.z));
    var strength : f32 = clamp(s, 0.0, 1.0);
    // If inverted, flip the strength (optional control)
    if (params.invert_flag > 0.5) {
        strength = 1.0 - strength;
    }
    let out_rgb : vec3<f32> = mix(base.xyz, vec3<f32>(0.0), strength);
    let out_color : vec4<f32> = vec4<f32>(out_rgb, base.w);
    let base_index : u32 = (gid.y * width + gid.x) * CHANNEL_COUNT;
    write_pixel(base_index, out_color);
}
